### ISSUE TITLE
missing 'model.csv' file?

### ISSUE THREAD

**Issue by YilinLiu97** [ozgurkara99/ISNAS-DIP#2]
Hi authors, thanks for the interesting work. I'm trying to run the nasdip.sh, and it seems that '/home/ersin/Documents/machine learning/NAS-DIP Summer Research/benchmark/models.csv' not uploaded?

**Comment by ozgurkara99** [comment]
Hello, thank you for your interest. You can find the "models.csv" file at our dataset, whose link is provided at the readme file.
