### ISSUE TITLE
Metrics calculated at initialization

### ISSUE THREAD

**Issue by FredXL1** [ozgurkara99/ISNAS-DIP#3]
Hi @ozgurkara99, I'm wondering about some of the details of the method: you mentioned that the metrics (PSD DB MSE etc.) were calculated **at initialization** with random CNN output and the corrupted image, does that mean you only passed the noise input into the model **once** without weight updating, and get the output from there?

**Comment by ozgurkara99** [comment]
Yes, with the "random output" we meant the output of the model when it is fed with a noise without performing any optimization step.
